version: '3'

tasks:
  meili_api_get_indexes:
    cmds:
      - xh http://localhost:7700/indexes

  run_build_bot:
    cmds:
      - docker exec -it -u tiger ailab zsh -c "source ~/.zshrc && cd /workspace/qna-assistant && npm run build"

  run_dev_bot:
    cmds:
      - docker exec -it -u tiger ailab zsh -c "source ~/.zshrc && cd /workspace/qna-assistant && npm run dev"

  test_bot:
    cmds:
      - docker exec -it -u tiger ailab zsh -c "source ~/.zshrc && cd /workspace/qna-assistant && npm test"

