export const ROOT_DIALOG = 'ROOT_DIALOG';
export const WATERFALL_DIALOG = 'WATERFALL_DIALOG';
export const USER_PROFILE_PROPERTY = 'USER_PROFILE_PROPERTY';
export const DIALOG_STATE_PROPERTY = 'DIALOG_STATE_PROPERTY';
