# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newspaper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnewspaper.proto\x12\tnewspaper\" \n\x10NewspaperRequest\x12\x0c\n\x04html\x18\x01 \x01(\t\"!\n\x0eNewspaperReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2N\n\tNewspaper\x12\x41\n\x05Parse\x12\x1b.newspaper.NewspaperRequest\x1a\x19.newspaper.NewspaperReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'newspaper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NEWSPAPERREQUEST']._serialized_start=30
  _globals['_NEWSPAPERREQUEST']._serialized_end=62
  _globals['_NEWSPAPERREPLY']._serialized_start=64
  _globals['_NEWSPAPERREPLY']._serialized_end=97
  _globals['_NEWSPAPER']._serialized_start=99
  _globals['_NEWSPAPER']._serialized_end=177
# @@protoc_insertion_point(module_scope)
